name: Build image

on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action push
  push:

env:
  DOCKER_IMAGE_NAME: nginx
  DOCKER_REGISTRY_URL: cr.yandex
  DOCKER_REGISTRY_ID: crp3d0vsnc3no3t2sntn

jobs:
  build_docker_images:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    environment: prod
    # Runner to use
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:${{ github.sha }}

    # Tag the Docker Images

    - name: Create a latest image as well
      run: docker tag $DOCKER_IMAGE_NAME:${{ github.sha }} $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_ID/$DOCKER_IMAGE_NAME:${{ github.sha }}

    - name: Login to Yandex registry
      run: echo ${{ secrets.YA_OAUTH }} | docker login --username oauth --password-stdin cr.yandex

    # Push the images to the registry
    - name: Push the Docker image with version number
      run: docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_ID/$DOCKER_IMAGE_NAME:${{ github.sha }}

    - name: Remove the local image
      run: docker rmi $DOCKER_IMAGE_NAME:${{ github.sha }}
