name: Deploy prod

on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when I create or push a `release/**` branch
  pull_request:
    types: closed
    branches:
      - 'release/**'

env:
  DOCKER_IMAGE_NAME: nginx
  DOCKER_REGISTRY_URL: cr.yandex
  DOCKER_REGISTRY_ID: crp3d0vsnc3no3t2sntn

jobs:
  deploy_on_kuber:
    name: Deploy Images on kuber
    environment: prod
    # Runner to use
    # runs-on: self-hosted
    runs-on: master-1

    steps:
    - uses: actions/checkout@v4
      with:
        repository: StackAls/nl-diplom
        path: nl-diplom
        sparse-checkout: |
          kuber/myapp.yml
        sparse-checkout-cone-mode: false

    - name: kuber deploy
      run: kubectl apply -f kuber/myapp.yml

  check_site:
    needs: deploy_on_kuber
    name: Curl check site
    runs-on: ubuntu-latest

    steps:
      - name: curl check
        run: curl -I http://178.154.205.25:30111
